stages:
  - static
  - tests
  - test # Gitlab security scans

# Documentation for using uv in the GitLab CI: https://docs.astral.sh/uv/guides/integration/gitlab/
variables:
  GITLAB_ADVANCED_SAST_ENABLED: "true"
  SAST_EXCLUDED_PATHS: public
  PYTHON_VERSION: 3.13
  BASE_LAYER: bookworm
  UV_LINK_MODE: copy
  UV_IMAGE: registry.cern.ch/ghcr.io/astral-sh/uv:python$PYTHON_VERSION-$BASE_LAYER
  UV_CACHE_DIR: .uv-cache

linters:
  stage: static
  image: $UV_IMAGE
  script:
    - uv run pre-commit run --all-files --show-diff-on-failure
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pytest:
  stage: tests
  image: $UV_IMAGE
  coverage: '/^TOTAL.+?(\d+\%)$/'
  script:
    - uv run pytest --cov-fail-under=80 -vvv
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

include: # https://docs.gitlab.com/ee/user/application_security/#use-security-scanning-tools-with-merge-request-pipelines
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/dependency_scanning/index
  - template: Jobs/SAST.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/sast/index
  - template: Jobs/Secret-Detection.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/secret_detection/index
  # If you push containers to the registry, use this to enable container scanning
  # - template: Jobs/Container-Scanning.gitlab-ci.yml #https://gitlab.cern.ch/help/user/application_security/container_scanning/index
